services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
      ]
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    depends_on:
      - mysql
    profiles: ["app"]

volumes:
  mysql-data: